using System;
using System.Collections.Generic;

namespace Infrastructure.Db.Dtoes.Pg
{
    public partial class Vovaonlineorder
    {
        public string Hasflammable { get; set; }
        public string Name4 { get; set; }
        public string Hasbattery { get; set; }
        public string Address { get; set; }
        public double? Logisticsproductid { get; set; }
        public string Haspowder { get; set; }
        public double? Height1 { get; set; }
        public string Addressen { get; set; }
        public string Descriptionlocal1 { get; set; }
        public string Streetaddress12 { get; set; }
        public string Streetaddress11 { get; set; }
        public string Zipcode { get; set; }
        public string Street { get; set; }
        public string Logisticstrackingnumber { get; set; }
        public string Descriptionlocal { get; set; }
        public string Descriptionen { get; set; }
        public string Payername { get; set; }
        public string City2 { get; set; }
        public double? Quantity1 { get; set; }
        public double? Weight1 { get; set; }
        public string City1 { get; set; }
        public string Mobile1 { get; set; }
        public string Incoterm { get; set; }
        public string Country { get; set; }
        public string Phone1 { get; set; }
        public string Name3 { get; set; }
        public DateTime? Utcmodifytime { get; set; }
        public string Pricecurrency { get; set; }
        public string Name2 { get; set; }
        public string Name1 { get; set; }
        public string Apikey { get; set; }
        public string Vovapostordersn { get; set; }
        public string Vovapostordertime { get; set; }
        public string Dimensionunit { get; set; }
        public string Timestamp { get; set; }
        public DateTime? Utccreatetime { get; set; }
        public string Descriptionen1 { get; set; }
        public double? Width { get; set; }
        public string Payerid { get; set; }
        public string Flytorderid { get; set; }
        public string Payercontactname { get; set; }
        public string Isliquid { get; set; }
        public string Countrycode1 { get; set; }
        public string District1 { get; set; }
        public string Mobile { get; set; }
        public string District2 { get; set; }
        public string Producturl { get; set; }
        public double? Length { get; set; }
        public string Payerphone { get; set; }
        public double? Length1 { get; set; }
        public string Company { get; set; }
        public string Email { get; set; }
        public string Payermobile { get; set; }
        public string Countryoforigin { get; set; }
        public string Addresslocal { get; set; }
        public double? Declarevalue { get; set; }
        public string Street2 { get; set; }
        public string Street1 { get; set; }
        public string Name { get; set; }
        public string Hasmetal { get; set; }
        public string Province1 { get; set; }
        public string Province2 { get; set; }
        public string Createflytordererrormsg { get; set; }
        public string Imageurl { get; set; }
        public string City { get; set; }
        public double? Weight { get; set; }
        public string Province { get; set; }
        public string Countryoforigincode { get; set; }
        public string Weightunit1 { get; set; }
        public string Apiusername { get; set; }
        public string Country2 { get; set; }
        public string Email1 { get; set; }
        public string Hasbattery1 { get; set; }
        public string Country1 { get; set; }
        public double? Dataversion { get; set; }
        public double? Pickuptype { get; set; }
        public string Id { get; set; }
        public string District { get; set; }
        public string Isflammable { get; set; }
        public string Requirelabel { get; set; }
        public string Weightunit { get; set; }
        public string Payeremail { get; set; }
        public double? Declarevalue1 { get; set; }
        public string Streetaddress2 { get; set; }
        public string Streetaddress1 { get; set; }
        public string Streetaddress21 { get; set; }
        public string Phone { get; set; }
        public string Streetaddress22 { get; set; }
        public string Paidwithvova { get; set; }
        public double? Height { get; set; }
        public string Ispowder { get; set; }
        public string Countrycode { get; set; }
        public DateTime? Utccanceltime { get; set; }
        public string Vovaplatformid { get; set; }
        public string Hscode { get; set; }
        public double? Quantity { get; set; }
        public string Iscreateflytorder { get; set; }
        public string Istest { get; set; }
        public string Priceunit { get; set; }
        public string Company1 { get; set; }
        public string Hasmetal1 { get; set; }
        public double? Width1 { get; set; }
        public string Hasliquid { get; set; }
        public string Zipcode1 { get; set; }
    }
}
